name: Download Model

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs -y
          git lfs install

      - name: Clone SmolLM2
        run: |
          mkdir -p model
          git clone https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct model/SmolLM2

      - name: List Files
        run: |
          ls -R model